backend:
  name: github
  repo: rhahloth256/Cloth-Shop-Website # Your GitHub repo
  branch: main # Make sure this matches your repo’s default branch
  auth_scope: repo # (optional) ensures proper repo permissions

# Where uploaded images are stored and accessed
media_folder: "assets/img/uploads" # Path inside the repo
public_folder: "/assets/img/uploads" # Public URL path on your website

logo_url: "/assets/img/transparent-logo.png" # Optional CMS logo (appears on login)

# Optional: Customize the CMS title and slug behavior
site_url: "https://yourdomain.com" # Replace with your actual domain
display_url: "https://yourdomain.com" # For previews

collections:
  - name: "products" # Internal name
    label: "Products" # UI label in CMS
    label_singular: "Product"
    description: "Manage all HaRié products displayed on the site."
    format: "json" # Important: JSON format
    files:
      - file: "data/products.json" # Path to your JSON file
        label: "Product List"
        name: "products"
        fields:
          - label: "Products"
            name: "products"
            widget: "list"
            summary: "{{fields.name}} — {{fields.category}}" # Displays product summary
            allow_add: true
            collapsed: false
            fields:
              - {
                  label: "ID",
                  name: "id",
                  widget: "string",
                  hint: "Unique lowercase identifier",
                }
              - { label: "Name", name: "name", widget: "string" }
              - {
                  label: "Category",
                  name: "category",
                  widget: "select",
                  options: ["men", "women", "bags", "shoes"],
                }
              - {
                  label: "Image",
                  name: "image",
                  widget: "image",
                  media_library: { allow_multiple: false },
                }
              - {
                  label: "Price (UGX)",
                  name: "price",
                  widget: "number",
                  value_type: "int",
                  min: 0,
                  step: 500,
                }
              - { label: "Description", name: "description", widget: "text" }
              - {
                  label: "Featured",
                  name: "featured",
                  widget: "boolean",
                  default: false,
                }
              - {
                  label: "In Stock",
                  name: "in_stock",
                  widget: "boolean",
                  default: true,
                }
              - {
                  label: "Has Promotion",
                  name: "has_promo",
                  widget: "boolean",
                  default: false,
                  required: false,
                }
              - {
                  label: "Badge Label",
                  name: "badge",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "Discount (%)",
                  name: "discount",
                  widget: "number",
                  required: false,
                  min: 0,
                  max: 100,
                }
