backend:
  name: github
  repo: Rhahloth/HaRie
  branch: main
  base_url: https://harriecollection-oauth.raysokello.workers.dev
  auth_endpoint: auth

site_url: https://harriecollection.pages.dev
media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"
logo_url: "/assets/img/transparent-logo.png"

collections:
  - name: "products"
    label: "Products"
    label_singular: "Product"
    description: "Manage all HaRié products displayed on the site."
    format: "json"
    files:
      - file: "data/products.json"
        label: "Product List"
        name: "products"
        fields:
          - label: "Products"
            name: "products"
            widget: "list"
            summary: "{{fields.name}} — {{fields.category}}"
            fields:
              - {
                  label: "ID",
                  name: "id",
                  widget: "string",
                  hint: "Unique lowercase identifier",
                }
              - { label: "Name", name: "name", widget: "string" }
              - {
                  label: "Category",
                  name: "category",
                  widget: "select",
                  options: ["men", "women", "bags", "shoes"],
                }
              - { label: "Image", name: "image", widget: "image" }
              - {
                  label: "Price (UGX)",
                  name: "price",
                  widget: "number",
                  value_type: "int",
                  min: 0,
                }
              - { label: "Description", name: "description", widget: "text" }
              - {
                  label: "Featured",
                  name: "featured",
                  widget: "boolean",
                  default: false,
                }
              - {
                  label: "In Stock",
                  name: "in_stock",
                  widget: "boolean",
                  default: true,
                }
              - {
                  label: "Has Promotion",
                  name: "has_promo",
                  widget: "boolean",
                  default: false,
                  required: false,
                }
              - {
                  label: "Badge Label",
                  name: "badge",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "Discount (%)",
                  name: "discount",
                  widget: "number",
                  required: false,
                  min: 0,
                  max: 100,
                }
